linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gosec
    - typecheck
    - revive
    - stylecheck

  disable:
    - errchkjson

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true

  gosec:
    severity: medium
    confidence: medium

  revive:
    severity: warning

  staticcheck:
    checks: ["all"]

issues:
  max-issues-per-linter: 50

  max-same-issues: 10

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - webapp
  tests: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
